# Dockerfile.inference
FROM python:3.9-slim-buster 
# Use Python 3.9
# ... rest of your Dockerfile

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/* # Clean up apt cache to keep image small

COPY /inference_app ./

# Install dependencies
COPY requirements3.txt .
RUN pip install --no-cache-dir -r requirements3.txt

# Run the script
CMD ["python", "main.py"]
