version: '3.8'

services:
  flask-app:
    # build:
    #   context: ./app
    #   dockerfile: Dockerfile.flask
    image: flask-app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

  streamlit-app:
    # build:
    #   context: ./streamlit_app 
    #   dockerfile: Dockerfile.streamlit
    image: streamlit-app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask-app
