# Dockerfile.flask
FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Install libgomp for LightGBM
RUN apt-get update && apt-get install -y libgomp1 && apt-get clean

COPY /app ./

# Install dependencies
COPY requirements1.txt .
RUN pip install --no-cache-dir -r requirements1.txt

EXPOSE 5000


# Run the Flask app
CMD ["python", "main.py"]

#code for image build