# Dockerfile.inference
FROM python:3.9-slim-buster 
# Use Python 3.9
# ... rest of your Dockerfile

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/* # Clean up apt cache to keep image small

COPY /manual_retrain ./

# Install dependencies
COPY requirements4.txt .
RUN pip install --no-cache-dir -r requirements4.txt

# Run the script
CMD ["python", "manual_retrain.py"]
