# Dockerfile.inference
FROM python:3.10-slim

WORKDIR /app

COPY /inference_app ./

# Install dependencies
COPY requirements3.txt .
RUN pip install --no-cache-dir -r requirements3.txt

# Run the script
CMD ["python", "main.py"]
